version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=checky
    volumes:
      - db_volume:/var/lib/postgresql/data
  db_test:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=checky_test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
volumes:
  db_volume: